language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: share-my-ideas
  api_key:
    secure: ZG5bH5RXf6FhH59XmJ3XkLHhVsQ94DN0KruptYH2RAF1QGwiIuNY9mnDy9oZ/nbxGLGPp4ccgeNWN0goZxNqLo5WdG++MTKM/scT4tkmJ0z4BklvnJ5a68a3MX+e5Y4byZXhFGnra6936oZ6t5fkH/HnxqFzWwXzLgoq+xfbxBKOaJatjCPmcduxVyp0YWLbauB+kwi/WcbeFQWrYDzJj1a5S3Rxf3aRagfaW6AyHL94HWlIfRFXGEtHWlqPosqoLhmPByNIN/j61lHwPHD1aJtwEjP/Hja9RlEaLqX+5XWaM3FK/8Lux8RpYN7r/Wb1uwV68edz30fPPViOgxorroApAbmYqQlA2OTGT5o1t3Z//v0i02wgdcYy+RehYm6M2KcPcRuDdfb886GTGDSyoHFGOnKBb8Uk5IOHpeh/BAs3KNsVqdQFF8qh9YHIaupT11AvcvCYC+nA0oIbqq50XaA39rlW4sqXgsoLAESZxobRdfC9XjxbcvztpzBdAZUl7UfQSFAj2HHVu+gIIHy7TgZehwdr6av4McDVg0aY2IFmyIQL1wB/jbuekAWRs4S6I5cjbc6nkmQQP4dF7TyT7AyqNBQ+Hv2+7flsv3y5rq/+/XsnKBNW5hGGFdXMc0GJRTMkdGbaLLzoh83fMNSmOM3yaocSuxfjf0kXp9C/jdw=
