language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: share-my-ideas
  api_key:
    secure: LUJHrIqArSKdgUtyVQCxYrFaQg3/sefo+Esx38mmp0PCOTyGA/ex/H+tqQ6qdS0nSqUrmzVv1XUkTzdnmKlWVpgcAskfy3GP+AKq81D7Bia4m3J97In2F5X+0cROCWXjA/Z6hItCZqm2daAJBMREyEww+M8uNBMfS6gI4UBp/af3YWsQgvm2KhDQ5igbxwySKPPXaSXGylDts6mr6ktvNXyIp4pv89cJbS3zVQOHF1zeP52PAs4ZISxAmssWqEM4mavoNfBSGIuXWo2TOZLo+i/HmtPcOj8RzVpCPGySWhdNq4OBDncUwVMH5qIfatPhWrvW8Lfh9jgiispcLlI2fFEDKz2jukLXEnI1wy7mkuR4zWf+AVAbWVK2NifHJ7yF/84/N35p12eCn+QiEQeXxkO3mH5rPhBDplfwem96jkJB9Pvnfw/nAZv56nYlBYwIsLLE6ozTanmJ8TGJlR9wq0bKG2NQfbOhCprQ7HY3Lxo0H+U1NiP7MIIvmIS/Xw0oSyhDu308s0hPPyWoJcYyWzJK+VNyFJqYF0lzXHz95130uOWvF4S3WP/iQ8c559/eDii9zVEbPddbcqhQAo01d2j05AARdV+kSwBzYJ4iaGnbWvtEXXpwopGoYarjo2WQ2IXnyoiR56D9gp3LTs1vMSGdXaYZ8xa6V37GHkE0Dvs=
